export const ErrorCode = {
  UNAUTHORIZED: "INTERVIEW_UNAUTHORIZED",
  RATE_LIMITED: "INTERVIEW_RATE_LIMITED",
  PAYLOAD_TOO_LARGE: "INTERVIEW_PAYLOAD_TOO_LARGE",
  INVALID_JSON: "INTERVIEW_INVALID_JSON",
  INVALID_REQUEST: "INTERVIEW_INVALID_REQUEST",
  CANDIDATE_REQUIRED: "INTERVIEW_CANDIDATE_REQUIRED",
  TURN_IN_FLIGHT: "INTERVIEW_TURN_IN_FLIGHT",
  MISCONFIGURED: "INTERVIEW_MISCONFIGURED",
  INTERNAL: "INTERVIEW_INTERNAL_ERROR",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
